# Build and autotest script for PX4 Firmware
# http://travis-ci.org

sudo: required
dist: xenial
services:
  - docker

language: cpp

git:
  depth: 2000
  submodules: false

cache:
  ccache: true

before_install:
  # install dependencies for the coverity build (target and branch), otherwise exit early
  - if [[ "${TRAVIS_BRANCH}" = "coverity_scan" ]]; then
      sudo pip install empy jinja2 numpy toml;
      echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-;
    fi
  # use git:// to fetch instead of https://
  - git config --global url."git://".insteadOf https://

env:
 - BUILD_TARGET=px4fmu-v2_default
 - BUILD_TARGET=px4fmu-v2_lpe
 - BUILD_TARGET=px4fmu-v3_default
 - BUILD_TARGET=px4fmu-v4_default
 - BUILD_TARGET=px4fmu-v5_default

stage: Build

script:
 - ./Tools/docker_run.sh make ${BUILD_TARGET}

jobs:
  include:
    - stage: Tests
      name: Self-tests
      script: PX4_DOCKER_REPO="px4io/px4-dev-simulation:2019-10-04" ./Tools/docker_run.sh make tests
    - stage: Tests 
      name: Mission test
      script: PX4_DOCKER_REPO="px4io/px4-dev-ros:2018-03-30" ./Tools/docker_run.sh make tests_mission
    - stage: Tests
      name: Offboard test
      script: PX4_DOCKER_REPO="px4io/px4-dev-ros:2018-03-30" ./Tools/docker_run.sh make tests_offboard
    - stage: Annotate
      name: Auto-generate changelog
      language: python
      python: 3.6
      install:
        - pip install GitPython PyGithub
      script:
        - python ./gen_changelog.py

stages:
  - Tests
  - Build
  - Annotate

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file:
    - build/**/*px4fmu*.px4
# FIXME: pack .elf files into a zip archive
#    - build/**/*px4fmu*.elf
  skip_cleanup: true
  on:
    tags: true
  prerelease: true
  draft: true
  name: ${TRAVIS_TAG}

#addons:
#  coverity_scan:
#    project:
#      name: "PX4/Firmware"
#      description: "Build submitted via Travis CI"
#    notification_email: ci@px4.io
#    build_command_prepend: "make distclean"
#    build_command: "make posix_sitl_default"
#    branch_pattern: coverity_scan
