sudo: required
dist: xenial
services:
  - docker

language: cpp

git:
  depth: 100
  submodules: false

cache:
  ccache: true

env:
 - BUILD_TARGET=px4_fmu-v2_default
 - BUILD_TARGET=px4_fmu-v2_lpe
 - BUILD_TARGET=px4_fmu-v3_default
 - BUILD_TARGET=px4_fmu-v4_default
 - BUILD_TARGET=px4_fmu-v5_default

stage: Build

script:
  - ./Tools/docker_run.sh make ${BUILD_TARGET}

jobs:
  include:
    - stage: Tests
      name: Self-tests
      script: PX4_DOCKER_REPO="px4io/px4-dev-simulation:2018-03-30" ./Tools/docker_run.sh make tests
    # FIXME: Make mission tests work again
    #- stage: Tests
    #  name: Mission test
    #  script: PX4_DOCKER_REPO="px4io/px4-dev-ros:2018-03-30" ./Tools/docker_run.sh make tests_mission
    - stage: Tests
      name: Offboard test
      script: PX4_DOCKER_REPO="px4io/px4-dev-ros:2018-03-30" ./Tools/docker_run.sh make tests_offboard
    - stage: Annotate
      name: Auto-generate changelog
      language: python
      python: 3.6
      install:
        - pip install GitPython PyGithub
      script:
        - python ./gen_changelog.py

stages:
 - Tests
 - Build
 - Annotate

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file:
    - build/**/*px4_fmu*.px4
    - build/**/*px4_fmu*.elf
  skip_cleanup: true
  on:
    tags: true
  prerelease: true
  draft: true
  name: ${TRAVIS_TAG}
